name: Build With Github
on: [push]
jobs:
  Build-Linux:
    strategy:
      matrix:
        godot_cpp_branch: [4.1, 4.2, 4.3]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # clone current repo
      - uses: actions/checkout@v4
      # clone required Godot source code into subfolder
      - uses: actions/checkout@v4
        with:
          repository: 'godotengine/godot-cpp'
          ref: ${{ matrix.godot_cpp_branch }}
          path: 'godot-cpp'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      # install SCons
      - run: python -m pip install scons
      # compile (debug)
      - run: scons target=template_debug
      # compile (release)
      - run: scons target=template_release