name: Build With Github
on: [push]
jobs:
  Build-Linux:
    strategy:
      matrix:
        godot_cpp_branch: [4.1, 4.2, 4.3]
        os: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # clone current repo
      - uses: actions/checkout@v4
      # clone required Godot source code into subfolder
      - uses: actions/checkout@v4
        with:
          repository: 'godotengine/godot-cpp'
          ref: ${{ matrix.godot_cpp_branch }}
          path: 'godot-cpp'
          submodules: true
      - name: Install build dependencies
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: mingw-w64 scons
      # compile binaries (linux + windows)
      - name: build binaries
        if: ${{ matrix.os != 'macos-latest' }}
        run: |
          scons target=template_debug arch=x86_32
          scons target=template_release arch=x86_32
          scons target=template_debug arch=x86_64
          scons target=template_release arch=x86_64
          scons target=template_debug arch=x86_32 platform=windows
          scons target=template_release arch=x86_32 platform=windows
          scons target=template_debug arch=x86_64 platform=windows
          scons target=template_release arch=x86_64 platform=windows
      - name: build MacOS binaries
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          scons target=template_debug arch=x86_64
          scons target=template_release arch=x86_64
          scons target=template_debug arch=arm64
          scons target=template_release arch=arm64
          lipo -create demo/addons/tree3d/libtree3d.macos.template_release.framework/libtree3d.macos.template_release.arm64 demo/addons/tree3d/libtree3d.macos.template_release.framework/libtree3d.macos.template_release.x86_64 -output demo/addons/tree3d/libtree3d.macos.template_release.framework/libtree3d.macos.template_release.universal
          lipo -create demo/addons/tree3d/libtree3d.macos.template_debug.framework/libtree3d.macos.template_debug.arm64 demo/addons/tree3d/libtree3d.macos.template_debug.framework/libtree3d.macos.template_debug.x86_64 -output demo/addons/tree3d/libtree3d.macos.template_debug.framework/libtree3d.macos.template_debug.universal
      - name: archive built binaries (linux)
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        with:
          name: ${{ format('binaries-linux-godot{0}', matrix.godot_cpp_branch) }}
          if-no-files-found: 'error'
          path: |
            demo/addons/tree3d/libtree3d.linux.*
      - name: archive built binaries (windows)
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        with:
          name: ${{ format('binaries-windows-godot{0}', matrix.godot_cpp_branch) }}
          if-no-files-found: 'error'
          path: |
            demo/addons/tree3d/libtree3d.windows.*
      - name: archive built binaries (macos)
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          name: ${{ format('binaries-macos-godot{0}', matrix.godot_cpp_branch) }}
          if-no-files-found: 'error'
          path: |
            demo/addons/tree3d/libtree3d.*
