name: Build With Github
on: [push]
jobs:
  Build-Linux:
    strategy:
      matrix:
        godot_cpp_branch: [4.1, 4.2, 4.3]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # clone current repo
      - uses: actions/checkout@v4
      # clone required Godot source code into subfolder
      - uses: actions/checkout@v4
        with:
          repository: 'godotengine/godot-cpp'
          ref: ${{ matrix.godot_cpp_branch }}
          path: 'godot-cpp'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      # install SCons
      - run: python -m pip install scons
      # compile binaries
      - name: build binaries
        if: ${{ matrix.os != 'macos-latest' }}
        run: |
          scons target=template_debug arch=x86_32
          scons target=template_release arch=x86_32
          scons target=template_debug arch=x86_64
          scons target=template_release arch=x86_64
      - name: build MacOS binaries
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          scons target=template_debug arch=x86_64
          scons target=template_release arch=x86_64
          scons target=template_debug arch=arm64
          scons target=template_release arch=arm64
      - name: archive built binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('binaries-{0}-{1}', matrix.os, matrix.godot_cpp_branch) }}
          path: |
            demo/demo/addons/tree3d/libtree3d.*